name: ${project.artifactId}
main: ${mainClass}
version: ${project.version}
load: POSTWORLD
author: ${author}
depend: [AdvancedReplay]
softdepend: [Vulcan, Spartan, Matrix, GodsEye, Atlas, Kauri, Karhu, Themis, Soaroma]
api-version: 1.13
commands:
  replayreload:
      description: Reload config