name: ${project.artifactId}
main: ${mainClass}
version: ${project.version}
author: ${author}
depend: [AdvancedReplay]
softdepend: [Vulcan, Spartan, Matrix, GodsEye, Kauri, Atlas]
api-version: 1.13
commands:
  replayreload:
      description: Reload config