name: VulcanReplay
main: me.justindevb.VulcanReplay.VulcanReplay
version: 2.2
load: POSTWORLD
author: JustinDevB
depend: [AdvancedReplay]
softdepend: [Vulcan, Spartan, Matrix, GodsEye, Atlas, Kauri, Karhu, Themis]
api-version: 1.13
commands:
  replayreload:
      description: Reload config