name: VulcanReplay
main: me.justindevb.VulcanReplay.VulcanReplay
version: 1.8
author: JustinDevB
depend: [AdvancedReplay]
softdepend: [Vulcan, Spartan, Matrix, GodsEye]
api-version: 1.13
commands:
  replayreload:
      description: Reload config