name: VulcanReplay
main: me.justindevb.VulcanReplay.VulcanReplay
version: 2.0
load: POSTWORLD
author: JustinDevB
depend: [AdvancedReplay]
softdepend: [Vulcan, Spartan, Matrix, GodsEye, Kauri, Atlas]
api-version: 1.13
commands:
  replayreload:
      description: Reload config